services:
  - type: web
    name: ytvox-spleeter
    env: python
    buildCommand: |
      echo "python_version = '3.8'" > runtime.txt
      pip install -r requirements.txt
    startCommand: ./start.sh
    plan: free
    envVars:
      - key: PORT
        value: 10000